# Using node version 22.10.0
FROM node:22.11.0

# Set the working directory within docker image
WORKDIR /usr/src/app

# May need later on
COPY ./execution-tools/wait-for-it.sh /usr/src/app

# expose port 8000
EXPOSE 8000
